"""Turn the certified NEAR table into a CUDA device header.

Reads ../include/volfi/volfi_near_certified_tables.hpp and emits
volfi_near_certified_tables_cuda.cuh, in which every top-level `static const`
becomes `__constant__` (arrays) or `__device__ static const` (scalars), inside
namespace volfi_near_certified_gpu.

Values are copied VERBATIM -- byte-identical text, no reformatting, no reparsing
of the doubles -- so the device constants are bit-identical to the host ones by
construction.  This mirrors gpu/make_device_constants.py in the shipped tree.

Why __constant__ rather than __device__ or __shared__.  The driver launches one
kernel per occupied a-cell over a contiguous bucket slice, so `cell` is uniform
across every warp in the launch and every read of NC_ROWDEG, NC_ROWCOFF and
NC_COEFF is at a warp-uniform address.  That is the case constant memory is built
for: a uniform read broadcasts in a single transaction.  The whole table is
5.5 KB against the 64 KB constant bank, so it resides there permanently, which is
the structural difference from the shipped FAR table's 218 KB that has no choice
but global memory and L2.

Usage:  python make_near_cuda.py        (from volfi_test/gpu/)
Regenerate whenever ../include/volfi/volfi_near_certified_tables.hpp changes.
"""

import re
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / "include" / "volfi" / "volfi_near_certified_tables.hpp"
OUT = Path(__file__).resolve().parent / "volfi_near_certified_tables_cuda.cuh"

HEADER = """// volfi_near_certified_tables_cuda.cuh
// GENERATED by gpu/make_near_cuda.py from include/volfi/volfi_near_certified_tables.hpp -- DO NOT EDIT
//
// Every value below is copied verbatim from the host header, so the device table
// is bit-identical to the host table by construction.  Arrays become __constant__
// because the driver makes `cell` warp-uniform (one launch per occupied a-cell over
// a contiguous bucket slice), which turns every coefficient read into a broadcast.
#ifndef VOLFI_NEAR_CERTIFIED_TABLES_CUDA_CUH
#define VOLFI_NEAR_CERTIFIED_TABLES_CUDA_CUH
namespace volfi_near_certified_gpu {

"""

FOOTER = """
} // namespace volfi_near_certified_gpu
#endif // VOLFI_NEAR_CERTIFIED_TABLES_CUDA_CUH
"""


def book_headers():
    """The book-chart device headers.  Only the three double ARRAYS need a device
    home (template specialisations and constexpr scalars are constant expressions
    that device code may use directly, and they stay in the host header, which the
    .cu includes as well).  Each array block is copied verbatim, requalified
    __constant__ and renamed d_*, so the device coefficients are bit-identical to
    the host ones by construction."""
    src_dir = Path(__file__).resolve().parent.parent / "include" / "volfi"
    out_dir = Path(__file__).resolve().parent
    arr_re = re.compile(r"^static constexpr double (NB_COEFF|NB_A_EDGE|NB_TAU_HI)\s*\[")
    for L in (1, 2, 3):
        src = src_dir / ("volfi_near_book_tables_L%d.hpp" % L)
        if not src.exists():
            print("  (no %s yet, skipped)" % src.name)
            continue
        lines = src.read_text(encoding="utf-8").split(chr(10))
        out, keep, nblk = [], False, 0
        for line in lines:
            if arr_re.match(line):
                keep = True
                nblk += 1
                line = re.sub(r"^static constexpr double (\w+)", r"__constant__ double d_\1", line)
            if keep:
                out.append(line)
                if line.rstrip().endswith("};"):
                    keep = False
                    out.append("")
        guard = "VOLFI_NEAR_BOOK_TABLES_L%d_CUDA_CUH" % L
        head = [
            "// volfi_near_book_tables_L%d_cuda.cuh" % L,
            "// GENERATED by gpu/make_near_cuda.py from include/volfi/volfi_near_book_tables_L%d.hpp -- DO NOT EDIT" % L,
            "// The three double arrays of the host header, copied verbatim, requalified",
            "// __constant__ and renamed d_*.  Everything else in the host header is a constant",
            "// expression the device uses directly, so it is not duplicated here.",
            "#ifndef %s" % guard, "#define %s" % guard, "namespace volfi_near_book {", ""]
        foot = ["} // namespace volfi_near_book", "#endif // %s" % guard, ""]
        dst = out_dir / ("volfi_near_book_tables_L%d_cuda.cuh" % L)
        dst.write_text(chr(10).join(head + out + foot), encoding="utf-8")
        body = chr(10).join(lines)
        # verify: every literal of the three arrays appears unchanged, in order
        src_lits = []
        keep = False
        for line in lines:
            if arr_re.match(line): keep = True
            if keep:
                src_lits += re.findall(r"-?\d+\.\d+e?[-+]?\d*", line)
                if line.rstrip().endswith("};"): keep = False
        out_lits = re.findall(r"-?\d+\.\d+e?[-+]?\d*", chr(10).join(out))
        print("  book L%d: %d array blocks, %d numeric literals, byte-identical to the host header: %s"
              % (L, nblk, len(src_lits), "yes" if src_lits == out_lits else "NO"))


def rec_header():
    """The recurrence chart: its two double arrays NR_G and NR_P, requalified __constant__
    and renamed d_*; everything else in the host header is a constant expression."""
    src = Path(__file__).resolve().parent.parent / "include" / "volfi" / "volfi_near_rec_tables.hpp"
    dst = Path(__file__).resolve().parent / "volfi_near_rec_tables_cuda.cuh"
    if not src.exists():
        print("  (no volfi_near_rec_tables.hpp yet, skipped)"); return
    lines = src.read_text(encoding="utf-8").split(chr(10))
    arr_re = re.compile(r"^static constexpr double (NR_G|NR_P)\s*\[")
    out, keep, lits = [], False, []
    for line in lines:
        if arr_re.match(line):
            keep = True
            line = re.sub(r"^static constexpr double (\w+)", r"__constant__ double d_\1", line)
        if keep:
            out.append(line); lits += re.findall(r"-?\d+\.\d+e?[-+]?\d*", line)
            if line.rstrip().endswith("};"): keep = False; out.append("")
    guard = "VOLFI_NEAR_REC_TABLES_CUDA_CUH"
    head = ["// volfi_near_rec_tables_cuda.cuh  GENERATED by gpu/make_near_cuda.py -- DO NOT EDIT",
            "// NR_G and NR_P of the host header, copied verbatim, __constant__, renamed d_*.",
            "#ifndef %s" % guard, "#define %s" % guard, "namespace volfi_near_rec {", ""]
    foot = ["} // namespace volfi_near_rec", "#endif // %s" % guard, ""]
    dst.write_text(chr(10).join(head + out + foot), encoding="utf-8")
    out_lits = re.findall(r"-?\d+\.\d+e?[-+]?\d*", chr(10).join(out))
    print("  rec: %d numeric literals, byte-identical to the host header: %s" % (len(lits), "yes" if lits == out_lits else "NO"))


def wb_header():
    src = Path(__file__).resolve().parent.parent / "include" / "volfi" / "volfi_wb_tables.hpp"
    dst = Path(__file__).resolve().parent / "volfi_wb_tables_cuda.cuh"
    if not src.exists():
        print("  (no volfi_wb_tables.hpp yet, skipped)"); return
    lines = src.read_text(encoding="utf-8").split(chr(10))
    arr_re = re.compile(r"^static constexpr double (NW_G0|NW_F1|NW_P|NW_D)" + chr(92) + "s*" + chr(92) + "[")
    out, keep, lits = [], False, []
    for line in lines:
        if arr_re.match(line):
            keep = True
            line = re.sub(r"^static constexpr double (" + chr(92) + "w+)", r"__constant__ double d_" + chr(92) + "1", line)
        if keep:
            out.append(line); lits += re.findall(r"-?" + chr(92) + "d+" + chr(92) + "." + chr(92) + "d+e?[-+]?" + chr(92) + "d*", line)
            if line.rstrip().endswith("};"): keep = False; out.append("")
    guard = "VOLFI_WB_TABLES_CUDA_CUH"
    head = ["// volfi_wb_tables_cuda.cuh  GENERATED by gpu/make_near_cuda.py -- DO NOT EDIT",
            "// The four double arrays of the whole-book host header, verbatim, __constant__, renamed d_*.",
            "#ifndef %s" % guard, "#define %s" % guard, "namespace volfi_wb {", ""]
    foot = ["} // namespace volfi_wb", "#endif // %s" % guard, ""]
    dst.write_text(chr(10).join(head + out + foot), encoding="utf-8")
    out_lits = re.findall(r"-?" + chr(92) + "d+" + chr(92) + "." + chr(92) + "d+e?[-+]?" + chr(92) + "d*", chr(10).join(out))
    print("  wb: %d numeric literals, byte-identical to the host header: %s" % (len(lits), "yes" if lits == out_lits else "NO"))


def main():
    book_headers()
    rec_header()
    wb_header()
    if not SRC.exists():
        sys.exit("missing %s -- run gen/certified_near.py first" % SRC)
    text = SRC.read_text(encoding="utf-8")

    # Take everything between the namespace open and close, then requalify.
    i = text.index("namespace volfi_near_certified {")
    j = text.rindex("} // namespace volfi_near_certified")
    body = text[i + len("namespace volfi_near_certified {"):j]

    out, n_arr, n_sc = [], 0, 0
    # `static const <type> NAME[...] = {` -> __constant__ ; scalars -> __device__ static const
    for line in body.split("\n"):
        m = re.match(r"^static const (\w+)\s+(\w+)\s*\[", line)
        if m:
            out.append(re.sub(r"^static const ", "__constant__ ", line))
            n_arr += 1
            continue
        m = re.match(r"^static const (\w+)\s+(\w+)\s*=", line)
        if m:
            out.append(re.sub(r"^static const ", "__device__ static const ", line))
            n_sc += 1
            continue
        out.append(line)

    OUT.write_text(HEADER + "\n".join(out).strip("\n") + FOOTER, encoding="utf-8")

    # Verify: every double literal in the source appears unchanged in the output.
    src_lits = re.findall(r"-?\d+\.\d+e?[-+]?\d*", body)
    out_lits = re.findall(r"-?\d+\.\d+e?[-+]?\d*", OUT.read_text(encoding="utf-8"))
    same = src_lits == out_lits
    print("wrote %s" % OUT)
    print("  %d arrays -> __constant__, %d scalars -> __device__" % (n_arr, n_sc))
    print("  %d numeric literals, byte-identical to the host header: %s"
          % (len(src_lits), "yes" if same else "NO -- ABORT"))
    if not same:
        sys.exit(1)


if __name__ == "__main__":
    main()
