"""Device headers of the one-step UPPER chart (v0.3.1).

volfi_upper1_cuda.cuh     the constants of include/volfi/volfi_annulus_upper1_tables.hpp, verbatim, __device__.
volfi_device_mirrors.cuh  the device mirrors of the routed charts, cut verbatim out of volfi_gpu_book.cu into namespace vgb,
                          so that the book driver (volfi_near_certified_gpu.cu) can run the UPPER fallback in the same thread.
Usage:  python make_upper1_cuda.py      (from gpu/).  Regenerate after either source changes.
"""
import re
from pathlib import Path
here = Path(__file__).resolve().parent
t = (here.parent / "include" / "volfi" / "volfi_annulus_upper1_tables.hpp").read_text(encoding="utf-8").split(chr(10))
body = [re.sub(r"^static const ", "__device__ static const ", l) for l in t if l.startswith("static const")]
assert len(body) == 13, len(body)
(here / "volfi_upper1_cuda.cuh").write_text(
    "// volfi_upper1_cuda.cuh  GENERATED by gpu/make_upper1_cuda.py -- DO NOT EDIT" + chr(10) +
    "// ONE-STEP UPPER constants, verbatim from volfi_annulus_upper1_tables.hpp, __device__." + chr(10) +
    "#pragma once" + chr(10) + "namespace volfi_annulus_gpu { namespace upper1 {" + chr(10) + chr(10).join(body) + chr(10) + "} }" + chr(10), encoding="utf-8", newline=chr(10))
g = (here / "volfi_gpu_book.cu").read_text(encoding="utf-8")
i0 = g.index("__device__ static const double D_VA_LN2"); i1 = g.index("#if VGB_HOST_CHECK" + chr(10) + "int main()")
(here / "volfi_device_mirrors.cuh").write_text(
    "// volfi_device_mirrors.cuh  GENERATED by gpu/make_upper1_cuda.py from volfi_gpu_book.cu -- DO NOT EDIT" + chr(10) +
    "// The device mirrors of the routed charts (incl. the one-step UPPER), verbatim, in namespace vgb." + chr(10) + "#pragma once" + chr(10) +
    "namespace vgb {" + chr(10) + "namespace g = volfi_annulus_gpu;" + chr(10) + g[i0:i1] + "} // namespace vgb" + chr(10), encoding="utf-8", newline=chr(10))
print("wrote volfi_upper1_cuda.cuh and volfi_device_mirrors.cuh")
