"""Mechanically transform the volfi-annulus CONSTANT packs into a CUDA device header.

Reads the three small constant headers (broadrange, endpoint_vec, wing) and emits
volfi_constants_cuda.cuh: every top-level `static const` becomes
`__device__ static const`, all flattened into namespace volfi_annulus_gpu (matching
volfi_annulus_tables_cuda.cuh, which already carries the big generated tables the
same way).  Values are copied verbatim -- byte-identical text, no reformatting --
so the device constants are bit-identical to the host ones by construction.

Functions in the sources (wing's logH_series_d) are NOT extracted; portable code is
hand-mirrored in volfi_gpu_book.cu instead.

Usage:  python make_device_constants.py       (from the gpu/ folder)
Regenerate whenever the parent constant headers change.
"""
import re
import sys
from pathlib import Path

SOURCES = [
    "volfi_annulus_broadrange.hpp",
    "volfi_annulus_endpoint_vec.hpp",
    "volfi_annulus_wing.hpp",
]
# The CPU headers sit one level up in the development tree and in include/volfi
# in the published repository.  Resolve against both so the generator runs
# unchanged in either layout.
def _find_header(name):
    here = Path(__file__).resolve().parent
    for cand in (here.parent / "include" / "volfi" / name, here.parent / name):
        if cand.is_file():
            return cand
    raise SystemExit("cannot locate %s (looked in ../include/volfi and ..)" % name)

OUT = "volfi_constants_cuda.cuh"


def extract_static_consts(text, fname):
    """Yield the full text of every top-level `static const ...;` declaration."""
    decls = []
    i = 0
    n = len(text)
    while True:
        m = re.search(r'^\s*static const ', text[i:], re.M)
        if not m:
            break
        start = i + m.start()
        # find the terminating ';' at brace depth 0 (array initializers contain none
        # of ';' inside, but track braces defensively)
        j = i + m.end()
        depth = 0
        while j < n:
            ch = text[j]
            if ch == '{':
                depth += 1
            elif ch == '}':
                depth -= 1
            elif ch == ';' and depth == 0:
                break
            j += 1
        if j >= n:
            sys.exit(f"unterminated static const in {fname}")
        decls.append(text[start:j + 1].strip())
        i = j + 1
    return decls


def main():
    here = Path(__file__).parent
    out_lines = [
        "// volfi_constants_cuda.cuh -- GENERATED by make_device_constants.py.  DO NOT EDIT.",
        "// Device copies of the volfi-annulus constant packs (broadrange + endpoint_vec +",
        "// wing), flattened into volfi_annulus_gpu to match volfi_annulus_tables_cuda.cuh.",
        "// Values byte-identical to the host headers by mechanical transform.",
        "#ifndef VOLFI_CONSTANTS_CUDA_CUH",
        "#define VOLFI_CONSTANTS_CUDA_CUH",
        "namespace volfi_annulus_gpu {",
        "",
    ]
    total = 0
    for rel in SOURCES:
        src = _find_header(rel)
        text = src.read_text()
        decls = extract_static_consts(text, src.name)
        out_lines.append(f"// ==== from {src.name} ({len(decls)} constants) ====")
        for d in decls:
            out_lines.append("__device__ " + d)
        out_lines.append("")
        total += len(decls)
        print(f"  {src.name}: {len(decls)} constants")
    out_lines += ["} // namespace volfi_annulus_gpu", "#endif", ""]
    (here / OUT).write_text("\n".join(out_lines))
    print(f"wrote {OUT}  ({total} constants)")


if __name__ == "__main__":
    main()
