// volfi_annulus_endpoint_vec.hpp   (GENERATED by generate_endpoint_vec.py)
// ---------------------------------------------------------------------------
// NEW offline constants that VECTORIZE the LEFT and RIGHT endpoint charts of the
// broad-range volfi-annulus inverter.  With these tables the LEFT/RIGHT inner
// loops become pure branchless Clenshaw/rational kernels (NO libm exp/erfc, and
// log only via the reused, already-vectorized log2approx), so the scalar entry
// and every batch driver call the SAME inlines and stay BIT-IDENTICAL, while
// machine precision is preserved.  These SUPPLEMENT volfi_annulus_broadrange.hpp
// (Binv, LEFT finisher, seam curves) -- all of those constants are UNCHANGED.
// WING and the frozen CENTRAL table are untouched.
//
// ==== LEFT reformulated inner-loop recipe (per c; per-h scalars hoisted) ====
//   inv_expm1h, h, h2=h*h, h4=h2*h2, xt = 2*h2/LEFT_T_MAX - 1   [index pass]
//   rho = c * inv_expm1h
//   A   = binv(rho)              // regime a: k/(rho+.5) Cheb15 ; b1/b2: sqrt(Cheb)
//                                // in L = -full_log(rho), full_log(x) =
//                                //   BR_LN2*( exponent(x) + log2approx(mantissa(x)) )
//                                //   (EXISTING log2approx; scalar==SIMD bit-identical)
//   s   = h / A
//   x   = sigma0_poly(BR_K*s)                         // EXISTING erfinv kernel
//   xs  = 2*s/LEFT_S_MAX - 1
//   V2  = cheb1(LEFT_V2_CHEB,29, 0, LEFT_S_CHEB_MAX, s)   // <-- NEW (no exp, no series branch)
//   V4  = cheb1(LEFT_V4_CHEB,27, 0, LEFT_S_CHEB_MAX, s)   // <-- NEW
//   fin = clenshaw2(2,16, LEFT_FIN_COEFFS, xt, xs)        // EXISTING frozen finisher
//   v   = x + h2*V2 + h4*V4 + (h4*h2)*fin ;   w = v*v
//   Only div/sqrt (hardware) + Clenshaw fma loops.  NO exp, NO erfc, NO libm log.
//
// ==== RIGHT reformulated inner-loop recipe (per c; eh=exp(-h/2),ehp=exp(h)
//      precomputed ONCE per h in the scalar index pass, libm, broadcast) ====
//   gbar = 0.5*(1-c)*eh
//   x0   = -qnorm0(gbar)         // Acklam rational (QN_A/B/C/D); tail branch (p<QN_P_LOW)
//                                //   uses full_log = BR_LN2*(exp+log2approx(mant)); rel~1.1e-9
//   m    = SQRT_PI2 * erfcx_poly(x0*IS2)          // Mills EXACT via shared erfcx (NO per-quote table)
//   inv=1/x0; x2=-0.125*(inv-m); x4=0.5*x0*x2^2+0.125*x2*inv^2+((inv^3-inv+m)/3)/128
//   x    = x0 + h2*x2 + h4*x4
//   repeat RIGHT_NEWTON_STEPS (=6) FIXED (no early-exit, no free-zone skip; bit-identity):
//       vv=2x; cmC = (c<0.5)? c-black_otm : onem_otm-(1-c)      // masked select
//       black_otm/onem_otm price via Phi=0.5*erfc_shared, ehp=exp(h) (per-h scalar)
//       erfc_shared(t): a=|t|; e=erfcx_poly(a)*exp_neg(-a*a); (t>=0? e : 2-e)   // masked sign
//       gp = -BR_K*exp_neg(-0.5*x*x)*exp_neg(-h2/(8*x*x))
//       x -= 0.5*cmC*eh/gp
//   v = 2x ;  w = v*v.   NO Newton-with-libm, NO erfc, NO exp in the loop
//   (exp_neg: a in [-30,0]; Cody-Waite reduce a = -n*LN2 + r via (LN2_HI,LN2_LO),
//    r in [-ln2/2,ln2/2]; exp = 2^n * poly(EXP_C, r) using scalef/ldexp).
// ---------------------------------------------------------------------------
#ifndef VOLFI_ANNULUS_ENDPOINT_VEC_HPP
#define VOLFI_ANNULUS_ENDPOINT_VEC_HPP
namespace volfi_annulus_broadrange {

// ---- full-log by reuse (shared with binv's L-branch and qnorm0 tail) ----
static const double BR_LN2 = 6.93147180559945286e-01;   // ln 2

// ===================== LEFT: V2/V4 Chebyshev in s =====================
static const double LEFT_S_CHEB_MAX = 1.71150000000000002e+00;   // = LEFT_S_MAX
static const int LEFT_V2_CHEB_N = 29;
static const double LEFT_V2_CHEB[29] = {
  -9.08054448000193627e-04,-1.43935334657918504e-03,-7.17289837384120022e-04,
  -2.34444340488605565e-04,-6.25148871847392795e-05,-1.78805032059841767e-05,
  -4.88567348469558306e-06,-1.36044030029366442e-06,-3.75258156569928204e-07,
  -1.04011469054588227e-07,-2.87847645231658601e-08,-7.97823266298891036e-09,
  -2.21151412637255653e-09,-6.13454316675986080e-10,-1.70228863353184343e-10,
  -4.72592069985710144e-11,-1.31249132960239302e-11,-3.64637368660433308e-12,
  -1.01335279570724738e-12,-2.81699112022686993e-13,-7.83291346110777437e-14,
  -2.17853782575745305e-14,-6.06040804857262695e-15,-1.68626553668226333e-15,
  -4.69277253006565657e-16,-1.30615290032457214e-16,-3.63458501272304664e-17,
  -1.00634784802122340e-17,-2.60059615872323094e-18,
};
static const int LEFT_V4_CHEB_N = 27;
static const double LEFT_V4_CHEB[27] = {
  1.67732869840760129e-05,2.69763141016103192e-05,1.41638539811891186e-05,
  5.18330440640254911e-06,1.61842758774790643e-06,5.17189850660131871e-07,
  1.58554217741015390e-07,4.86003630507734627e-08,1.46870172155356049e-08,
  4.41810218971048835e-09,1.31987060958204977e-09,3.92587730515995841e-10,
  1.16259167093827871e-10,3.43078590882464524e-11,1.00915756329229443e-11,
  2.96014512768054024e-12,8.66108178610942145e-13,2.52844549431934888e-13,
  7.36628070356372439e-14,2.14209311434230487e-14,6.21860728663056917e-15,
  1.80249414892096477e-15,5.21714260950784934e-16,1.50800006077236779e-16,
  4.35142829589438762e-17,1.24697223414690008e-17,3.31767412840110002e-18,
};

// ===================== RIGHT: shared branchless kernels =====================
// erfcx(z) on [RIGHT_ERFCX_A, RIGHT_ERFCX_B]  (Mills seed + erfc in price/g')
static const double RIGHT_ERFCX_A = 0.00000000000000000e+00;
static const double RIGHT_ERFCX_B = 5.20000000000000018e+00;
static const int RIGHT_ERFCX_C_N = 36;
static const double RIGHT_ERFCX_C[36] = {
  3.45221633503515923e-01,-3.55004140280202163e-01,1.69567122040612389e-01,
  -7.62050143024314702e-02,3.25094398795304704e-02,-1.32511892990754814e-02,
  5.18676211729631256e-03,-1.95730774382782587e-03,7.14406738331644742e-04,
  -2.52882621976092113e-04,8.70083509143963952e-05,-2.91548749741489230e-05,
  9.53008777628971761e-06,-3.04336649406865430e-06,9.50702795810824337e-07,
  -2.90849266773234379e-07,8.72310905297822933e-08,-2.56718996016839057e-08,
  7.41982227348777283e-09,-2.10770859537125768e-09,5.88862090299027938e-10,
  -1.61913166651417675e-10,4.38403491899399863e-11,-1.16957345495991265e-11,
  3.07584083542641494e-12,-7.97790581213034062e-13,2.04171297477258162e-13,
  -5.15775653202546215e-14,1.28663615074794758e-14,-3.17057209686348133e-15,
  7.72067759059992408e-16,-1.85844380998745291e-16,4.42333447629576408e-17,
  -1.04119303065768101e-17,2.41894974458721691e-18,-5.30225002190389211e-19,
};

// exp_neg(a): Cody-Waite ln2 reduction + Chebyshev poly on [-ln2/2, ln2/2]
static const double LN2_HI  = 6.93147180369123816e-01;
static const double LN2_LO  = 1.90821492927058770e-10;
static const double INV_LN2 = 1.44269504088896339e+00;
static const int EXP_C_N = 13;
static const double EXP_C[13] = {
  1.03025449180961837e+00,3.51803207837704135e-01,3.03300103540964788e-02,
  1.74756361397688490e-03,7.55940398271200852e-05,2.61727190730189373e-06,
  7.55358006712673221e-08,1.86890638954323144e-09,4.04652290352491796e-11,
  7.78861300348690978e-13,1.34929553271864241e-14,2.12510840465984621e-16,
  3.06768039569340852e-18,
};

// qnorm0(p): Acklam rational seed (x0 = -qnorm0(gbar)); tail p<QN_P_LOW uses full_log
static const double QN_P_LOW  = 2.42500000000000007e-02;
static const double QN_P_HIGH = 9.75750000000000006e-01;
static const int QN_A_N = 6;
static const double QN_A[6] = {
  -3.96968302866537570e+01,2.20946098424520500e+02,-2.75928510446968687e+02,
  1.38357751867269002e+02,-3.06647980661471600e+01,2.50662827745923922e+00,
};
static const int QN_B_N = 5;
static const double QN_B[5] = {
  -5.44760987982240579e+01,1.61585836858040892e+02,-1.55698979859886606e+02,
  6.68013118877197201e+01,-1.32806815528857207e+01,
};
static const int QN_C_N = 6;
static const double QN_C[6] = {
  -7.78489400243029261e-03,-3.22396458041136480e-01,-2.40075827716183809e+00,
  -2.54973253934373378e+00,4.37466414146496785e+00,2.93816398269878309e+00,
};
static const int QN_D_N = 4;
static const double QN_D[4] = {
  7.78469570904146216e-03,3.22467129070039826e-01,2.44513413714299599e+00,
  3.75440866190741618e+00,
};
// ==== C2: two-piece erfcx on [0,2.0] U [2.0,5.2] (splits the serial Clenshaw chain
// 36 -> 22, halving the latency of the dominant kernel in the RIGHT finisher).  Fitted
// by high-precision DCT (mpmath dps=40, coefficients rounded to double); worst relative
// error 1.84e-16 (piece 0) / 6.2e-17 (piece 1) in exact arithmetic.  Supersedes the
// single-piece RIGHT_ERFCX_C above (kept for reference).
static const double RIGHT_ERFCX2_SPLIT = 2.0;
static const int    RIGHT_ERFCX2_N = 23;
static const double RIGHT_ERFCX2_C0[23] = {
  5.21360870499606222e-01,-3.44770745472523510e-01,9.97597792682009682e-02,
  -2.60636652564787581e-02,6.26846349431901036e-03,-1.40612238588706502e-03,
  2.96985572465489987e-04,-5.94855539010672422e-05,1.13629607611355208e-05,
  -2.07940786341477614e-06,3.65908212016697135e-07,-6.21072613636215914e-08,
  1.01953166992700508e-08,-1.62232278024696099e-09,2.50734067466620776e-10,
  -3.77038135937425603e-11,5.52487689823067845e-12,-7.89991297890002301e-13,
  1.10362131407593383e-13,-1.50799307155856736e-14,2.01742341199638620e-15,
  -2.64430350084960443e-16,3.34789956147088900e-17,
};
static const double RIGHT_ERFCX2_C1[23] = {
  1.65540755725950728e-01,-7.12865730151999860e-02,1.48437052081732881e-02,
  -2.99776861968896382e-03,5.88602284331089191e-04,-1.12589655514087458e-04,
  2.10177308516902520e-05,-3.83478717976476517e-06,6.84763459339031819e-07,
  -1.19809859168416544e-07,2.05612881377368221e-08,-3.46433708100899726e-09,
  5.73546369628910865e-10,-9.33744220098902914e-11,1.49589569698012916e-11,
  -2.35975050505600518e-12,3.66755999954682940e-13,-5.61914144532827351e-14,
  8.49106263852105135e-15,-1.26606379675906971e-15,1.86352677933752429e-16,
  -2.70779454364097113e-17,3.81268928640980728e-18,
};

// Third piece [5.2, 7.2], needed ONLY by the warm-start entry (whose basin W<=40, h<=16
// pushes the erfc arguments up to ~6.96; the cold RIGHT chart never exceeds ~4.6, so cold
// results are bit-unchanged by its existence).  Worst relative error 7.0e-18.
static const double RIGHT_ERFCX2_B2 = 7.2;
static const double RIGHT_ERFCX2_C2[23] = {
  9.09770714600740826e-02,-1.43970802574348421e-02,1.12557268845857881e-03,
  -8.69830606393667957e-05,6.64692604995736978e-06,-5.02439731735371209e-07,
  3.75808042900977610e-08,-2.78227573890511032e-09,2.03944120017233167e-10,
  -1.48052817011234327e-11,1.06470049259196166e-12,-7.58661793372890632e-14,
  5.35769524573600913e-15,-3.75068609876830909e-16,2.60336743855904226e-17,
  -1.79199574627157559e-18,1.22347720541345237e-19,-8.28684207507269219e-21,
  5.56916230737450057e-22,-3.71422675633927477e-23,2.45862161699512490e-24,
  -1.61553536951903449e-25,1.04957436073122060e-26,
};

static const double SQRT_PI2 = 1.25331413731550034e+00;   // sqrt(pi/2), Mills scale
// D: warm-start refinement (calibration loops re-inverting a moved surface).
// CONVERGENCE basin (50-digit oracle): 3 fixed HH3 steps converge from seeds off by up to
// +-10% for W<=15, +-5% for W<=30, +-2% for W<=50 (W = h^2/(2 w_prev)); caller guard W<=40.
// ACCURACY floor (measured vs the cold inverter, 6851 mixed-h pts): the (y,r) price
// representation rounds y and r by half an ulp each, which the deep-OTM price cancellation
// amplifies; the warm result is therefore accurate to a FEW ULP rather than the last bit:
// worst 2.9e-15 for W<=8 (any realistically traded quote), growing to ~1.3e-14 at W=40;
// median sub-ulp.  This floor is intrinsic to x-space polishing (the cold wing chart works
// in log-price space precisely to avoid it), so a calibrator wanting last-bit output should
// cold-invert the FINAL iterate; intermediate iterates gain nothing from that precision.
static const int WARM_HH3_STEPS = 3;
// Fast warm path for the live streaming regime (tick-to-tick / F-tick moves, where
// the vol moves sub-percent).  De-risked (2026-07-14, warm-vs-truth over W<=40,
// both move signs): 2 HH3 steps reach the SAME floor as 3 for |dv/v| <= 1% at every
// W; they diverge only for moves >= 2% at deep W (which the guard below catches).
static const int    WARM_HH3_FAST_STEPS = 2;
// Convergence guard: the last HH3 relative correction |dx/x|.  For a converged
// 2-step warm from a <=1% move it is ~1e-8; a move too large for 2 steps leaves it
// >~1e-7.  A caller using warm_variance_fast re-inverts cold when *ok comes back
// false (out-of-basin move), so the fast path never returns a low-accuracy result
// silently.
static const double WARM_FAST_TOL = 1e-6;
static const int    RIGHT_HH3_STEPS = 3;   // FIXED count of Householder-3 (order-4) steps,
                                           // no early-exit.  Replaces the former fixed-6 Newton:
                                           // the closed-form logarithmic derivative of the RIGHT
                                           // equation makes the 2nd/3rd derivatives (a=g''/g',
                                           // b=g'''/g') cheap rationals, so an order-4 step costs
                                           // one Newton step; 3 of them reach machine precision
                                           // with >10 orders of margin from the ladder seed even
                                           // at its worst point (near the wing seam, seed err 0.27).

} // namespace volfi_annulus_broadrange
#endif // VOLFI_ANNULUS_ENDPOINT_VEC_HPP
