// volfi_near_rec_tables.hpp   GENERATED by gen/certified_rec.py -- DO NOT EDIT
// The recurrence chart: one fitted function G(a) = 1/V_0(a) on [0, A_WING] and the
// exact rational rows P_m(y) of the tau series (rows_from_recurrence.py).
#ifndef VOLFI_NEAR_REC_TABLES_HPP
#define VOLFI_NEAR_REC_TABLES_HPP
namespace volfi_near_rec {

static constexpr double NR_A_WING  = 8.0509688130094172;
static constexpr double NR_TAU_MAX = 3.5000000000000000e-2;   // series valid for (h/a)^2 <= this
static constexpr double NR_SA      = 2.4841730808449234e-1;   // 2/A_WING : xa = fma(a, NR_SA, -1)
static constexpr int    NR_NG      = 25;      // Chebyshev terms of G, c_0 already halved
static constexpr int    NR_M       = 10;      // rows x^0 .. x^NR_M
static constexpr double NR_G[25] = {
  3.7481574449433358e-1,-2.9652608581918468e-2,-4.0191529317421706e-3,
  1.4251471099561197e-3,-1.2792076953568459e-4,-3.2861784077123851e-5,
  1.2684249791368101e-5,-1.1443084839906305e-6,-3.9011202052067540e-7,
  1.4702830674476795e-7,-1.2280873240036319e-8,-5.2715647408165411e-9,
  1.9031655401122570e-9,-1.4301569927250805e-10,-7.6043437105525088e-11,
  2.6222227720231697e-11,-1.7345098441401261e-12,-1.1423969311409576e-12,
  3.7618416331484823e-13,-2.1341550053174348e-14,-1.7646502252422627e-14,
  5.5497360121016868e-15,-2.6048030462414958e-16,-2.7810804869753564e-16,
  8.3545885007817180e-17,
};
// P_m(y) coefficients in the flat array NR_P, HIGHEST degree first, at NRRow<m>::off,
// NRRow<m>::deg + 1 of them (deg = m-1 for m >= 1); P_0 = 1.  Flat, so the device
// copy can live in __constant__ memory under one name.
template<int M> struct NRRow;
template<> struct NRRow<0> { enum { deg = 0, off = 0 }; };
template<> struct NRRow<1> { enum { deg = 0, off = 1 }; };
template<> struct NRRow<2> { enum { deg = 1, off = 2 }; };
template<> struct NRRow<3> { enum { deg = 2, off = 4 }; };
template<> struct NRRow<4> { enum { deg = 3, off = 7 }; };
template<> struct NRRow<5> { enum { deg = 4, off = 11 }; };
template<> struct NRRow<6> { enum { deg = 5, off = 16 }; };
template<> struct NRRow<7> { enum { deg = 6, off = 22 }; };
template<> struct NRRow<8> { enum { deg = 7, off = 29 }; };
template<> struct NRRow<9> { enum { deg = 8, off = 37 }; };
template<> struct NRRow<10> { enum { deg = 9, off = 46 }; };
static constexpr int    NR_NP = 56;
static constexpr double NR_P[56] = {
  1.0000000000000000,4.1666666666666667e-2,-3.4722222222222222e-4,
  3.6458333333333333e-3,5.5114638447971781e-6,-5.9937169312169312e-5,
  3.9372519841269841e-4,-1.0333994708994709e-7,1.1797977292768959e-6,
  -9.5847800925925926e-6,4.7030440503747795e-5,2.0876756987868099e-9,
  -2.4921628654267543e-8,2.2543635553618193e-7,-1.5113141062576826e-6,
  5.9608605039106341e-6,-4.4034917822395777e-11,5.4627434460299319e-10,
  -5.3153752325568766e-9,4.1335064263076795e-8,-2.3758435979305094e-7,
  7.8558297938146842e-7,9.5589546647747706e-13,-1.2255376459796654e-11,
  1.2600378384320964e-10,-1.0771397289657028e-9,7.4056118723815130e-9,
  -3.7342897007188308e-8,1.0643470641076666e-7,-2.1185501852016143e-14,
  2.7945030932813382e-13,-3.0024430192797618e-12,2.7487845391428423e-11,
  -2.1143570181216871e-10,1.3063015087535408e-9,-5.8732941896759477e-9,
  1.4720573016569312e-8,4.7700344757099136e-16,-6.4502339796834033e-15,
  7.1871922834902098e-14,-6.9398881680146652e-13,5.7825761808381761e-12,
  -4.0558900179172024e-11,2.2779229115126825e-10,-9.2454763286184314e-10,
  2.0686822057010531e-9,-1.0874343492790309e-17,1.5031112539787058e-16,
  -1.7274101330539824e-15,1.7416407246205578e-14,-1.5429375445758091e-13,
  1.1838925597669230e-12,-7.6424161243006322e-12,3.9368502602864758e-11,
  -1.4566406320564821e-10,2.9443076211318112e-10,
};

} // namespace volfi_near_rec
#endif
