// volfi_annulus_fastroute_tables.hpp -- GENERATED by reproduce/upper/gen_fastroute.cpp (v0.3.1).  Routing seams in the book coordinate.
#pragma once
namespace volfi_annulus { namespace fastroute {
static const double BAND[4] = { 0x1.0c6f7a0b5ed8dp-20, 0x1.3333333333333p-2, 0x1.a9c5c42f6f595p+2, 0x1.08p+4 };
static const int    ATOP_N[3] = { 6, 14, 14 };
static const double ATOP_M[3] = { 0x1.c8699812dea11p-40, 0x1.85e96f33025bdp-29, 0x1.a09ebccc096f5p-31 };   // margin = 4 x worst fit error + 1e-12
static const double ATOP_C0[6] = { 0x1.dc7818c7be589p-3, 0x1.dc92a059dad8dp-3, 0x1.06752752eb695p-14, 0x1.5da3f8dab32p-17, -0x1.ec77ce3355555p-29, -0x1.89670f5p-32 };
static const double ATOP_C1[14] = { 0x1.9773bfac65ab7p+2, 0x1.953d305988ba8p+2, 0x1.f176ff5b3144dp-2, 0x1.85f7c4ed4fc39p-5, -0x1.d34b4caf59509p-8, 0x1.8c6910847776ep-12, 0x1.0d97a0e271249p-13, -0x1.c045572f5adb7p-16, -0x1.35a9b0f944925p-19, 0x1.56cbaaf612492p-20, 0x1.2b8d2a4492492p-25, -0x1.2b6d9664p-24, 0x1.81f7769b6db6ep-29, 0x1.0bd253b6db6dbp-28 };
static const double ATOP_C2[14] = { 0x1.f817adc779162p+4, 0x1.3f4971a288ca5p+4, 0x1.afe75e206a689p+0, 0x1.5d1a0228ba6dbp-7, -0x1.86bfaa9d28492p-10, 0x1.d997f963b6db7p-13, -0x1.4009ff2c49249p-15, 0x1.eb641ba3b6db7p-18, -0x1.9dc87998p-20, 0x1.638588p-22, -0x1.21a0b5cp-24, 0x1.9d1688p-27, -0x1.b253e24924925p-30, 0x1.9b22924924925p-35 };
static const double* const ATOP_C[3] = { ATOP_C0, ATOP_C1, ATOP_C2 };
static const int    AW_N[3] = { 6, 14, 12 };
static const double AW_M[3] = { 0x1.33af33025bd42p-37, 0x1.5387bccc096f5p-31, 0x1.0b867799812dfp-28 };   // margin = 4 x worst fit error + 1e-12
static const double AW_C0[6] = { 0x1.01b0e9c18688dp+3, 0x1.48019e3802d55p-9, 0x1.47d7b1bac7555p-11, -0x1.79f8a66aaaaabp-23, -0x1.78ae135555555p-26, 0x1.9acp-36 };
static const double AW_C1[14] = { 0x1.1c169d09264cp+3, 0x1.090c00c8fe8e5p+0, 0x1.953ee2b277ec9p-3, -0x1.fefce40e106dbp-7, 0x1.c76135c1ab6dbp-12, 0x1.2e8dd904cdb6ep-12, -0x1.051612ee4p-14, 0x1.6233f60524925p-20, 0x1.00e73506p-19, -0x1.995d02bdb6db7p-22, -0x1.0e591f2492492p-28, 0x1.0442ecdb6db6ep-26, -0x1.5d7e049249249p-29, -0x1.0a1ec6db6db6ep-33 };
static const double AW_C2[12] = { 0x1.ad7f182e7e9a9p+3, 0x1.c43a5095f165dp+1, 0x1.8f99b1c1d250bp-3, -0x1.6cc6ba79d32p-7, 0x1.b1dd7cfd41555p-11, -0x1.a1897cb155555p-13, 0x1.da6564904aaabp-16, -0x1.d47cc76baaaabp-19, 0x1.70c1dc12aaaabp-22, 0x1.3363ff8p-27, -0x1.b1d7a48p-27, 0x1.e43e16aaaaaabp-29 };
static const double* const AW_C[3] = { AW_C0, AW_C1, AW_C2 };
static const int    CT0_N = 8;
static const double CT0_M = 0x1.0e126e1a84ae7p-45;   // margin on c, absolute
static const double CT0_C[8] = { 0x1.3c554e3233383p-1, -0x1.c0907288a1abp-6, -0x1.7416d37e0fcp-13, 0x1.5fd1d0886p-18, 0x1.164b1beep-24, -0x1.d1f235p-31, -0x1.100a1p-36, 0x1.abb8p-44 };
} } // namespace volfi_annulus::fastroute
