// volfi_annulus_broadrange.hpp  (GENERATED by generate_broadrange.py)
// ---------------------------------------------------------------------------
// NEW constants for the BROAD-RANGE extension of the volfi-annulus BS implied-
// vol inverter (v = sigma*sqrt(T) up to ~8, |x|=h up to ~16). Four charts tile
// the (h,c) domain with machine-precision overlap at every seam.
//
// Conventions: h=|log(K/F)|>=0, v=sqrt(w)=sigma*sqrt(T)>0, c in (0,1) OTM call,
//   c = Phi(-h/v+v/2) - e^h Phi(-h/v-v/2),  k = 1/sqrt(2*pi).
//
// ROUTING (SEAMS de-risk, order matters; c2(h),cwing(h) are the 1-D-in-h
// boundary prices emitted below):
//     cw = cwing(h);  ct2 = c2(h);
//     if      (c <  cw)                  -> WING            (true W>=3)
//     else if (h <  H_ATM_HI)            -> (c<=ct2 ? LEFT : RIGHT)
//     else if (h <= H_BOX && c <= ct2)   -> CENTRAL         (v<=2, in box)
//     else                               -> RIGHT
//
// PER-CHART RUNTIME RECIPE
// ------------------------
// WING  (existing volfi_annulus::wing_variance, unchanged): resurgent GL-40
//       evaluator; machine for W>=2.5. Seam at W=3.
//
// LEFT  (h<H_ATM_HI, c<=c2(h); replaces old small-h residual table+corner):
//   rho = c/expm1(h);  A = volfi_binv(rho);  s = h/A;
//   x   = sigma0_poly(k*s);                 // V0, existing erfinv kernel (k*s<=E2)
//   V2  = (s<LEFT_S_V2X)? series : (k/(2s)-k*s/12 - p/(2x))/p,  p=k*exp(-x^2/8)
//   V4  = (s<LEFT_S_V4X)? series : closed form (see de-risk)
//   xt = 2*h^2/LEFT_T_MAX-1;  xs = 2*s/LEFT_S_MAX-1;
//   v  = x + h^2*V2 + h^4*V4 + h^6*clenshaw2(2,16,LEFT_FIN_COEFFS,xt,xs);  w=v*v
//   FINISHER = single dp=2 x dl=16 factored residual cell (branchless, erf-free).
//   Free zone (no finisher needed): h <= LEFT_FREE_C * v^{-1/3}.
//
// RIGHT (v>2 / c>c2(h); replaces old out-of-box clamp; also covers v<=2 beyond
//        the box via Newton). 3-term erf-free seed + EXACT Newton finisher; NO
//        residual table (provably infeasible at the low-v/high-W corner):
//   gbar = 0.5*(1-c)*e^{-h/2};  x0 = -qnorm(gbar);   // LOWER TAIL (not (1+ct)/2)
//   p = k*e^{-x0^2/2};  m = gbar/p;   // Mills ratio EXACT, no erfc kernel
//   inv=1/x0; B1'=inv-m; x2=-B1'/8; B2'=(inv^3-inv+m)/3; x4=x0*x2^2/2+x2*inv^2/8+B2'/128;
//   x = x0 + h^2*x2 + h^4*x4;  v=2x;
//   FINISHER (skip if h<=RIGHT_FREE_C*v^1.5): Newton on the exact equation
//     g(x)=(1-C(h,2x))*e^{-h/2}/2 = gbar,  g'(x) = -k*e^{-x^2/2}*e^{-h^2/(8x^2)}
//     x -= (g(x)-gbar)/g'(x);  ~4-9 iters to 1e-16;  v=2x, w=v*v.
//   (Uses the existing Black pricer; for batch bit-identity run a FIXED step count.)
//
// SUPERSEDES: the old small-h residual table (SMH_* in volfi_annulus_tables.hpp)
//   is REPLACED by the LEFT matched chart. Keep it only as an alternative; it is
//   no longer on the routed path. The CENTRAL table and the WING are UNCHANGED
//   and still required. NO new 2-D table beyond the LEFT finisher cell.
// ---------------------------------------------------------------------------
#ifndef VOLFI_ANNULUS_BROADRANGE_HPP
#define VOLFI_ANNULUS_BROADRANGE_HPP
#include <cmath>
namespace volfi_annulus_broadrange {

// ---- shared constant ----
static const double BR_K = 0.3989422804014327;  // 1/sqrt(2*pi)

// ===================== 1. Binv evaluator =====================
// A = Binv(rho), rho in [RHO_STAR,+inf), A in (0, 2.4510196252]. 3 branchless
// Chebyshev regimes (Clenshaw). B(A)=phi(A)/A-Phi(-A), decreasing bijection.
// Domain EXTENDED to A_MAX (max A on the W=3 / cwing boundary) so the LEFT
// chart never extrapolates Binv; wing takes W>3 (clean overlap at W=3).
static const double BINV_RHO_A = 0.39559311480261206;  // = B(0.5)
static const double BINV_RHO_B = 0.0833154705876863;  // = B(1.0)
static const double BINV_U2_A  = 0.0, BINV_U2_B = 0.1984260281970251;
static const double BINV_L_B1A = 0.9273690838273746, BINV_L_B1B = 2.4851210257126413;
static const double BINV_L_B2A = 2.4851210257126413, BINV_L_B2B = 6.958307262339952;
// regime a: u=k/(rho+0.5), x=u*u; A = u*clenshaw(BINV_CA,U2_A,U2_B,x)
static const double BINV_CA[15] = {
  1.0579386227197838,0.061016433372780884,0.0032759766479894515,
  0.00021218527376998432,1.5068159412817706e-05,1.130318453260047e-06,
  8.79297297436825e-08,7.019715691335284e-09,5.713760401938888e-10,
  4.7213000205742066e-11,3.948423950026458e-12,3.3346711119738485e-13,
  2.839246968109063e-14,2.4309045617698024e-15,2.0387724283411997e-16,
};
// regime b1/b2: L=log(1/rho); A2=clenshaw(...); A=sqrt(A2)
static const double BINV_CB1[17] = {
  0.5848458244566864,0.37468890292980295,0.04030791601709246,
  0.00030528257303590175,-0.00015446530681508498,5.9108340076427e-06,
  7.237769705709067e-07,-9.711665251754396e-08,1.1299930437510735e-09,
  7.810092688083641e-10,-7.47542247435787e-11,-1.1423954198851336e-12,
  8.297325463470093e-13,-6.173231911997356e-14,-2.858488365525312e-15,
  8.907966576990864e-16,-5.2280888051237656e-17,
};
static const double BINV_CB2[25] = {
  3.303710581428976,2.5229256900484107,0.19895331328871727,
  -0.019289014765776193,0.0011345259364056643,0.00010239480476770851,
  -4.8710309692501305e-05,9.511659329728526e-06,-1.1369961620359819e-06,
  2.853568437812938e-08,2.6789832680264564e-08,-8.441246095360667e-09,
  1.546108503738377e-09,-1.6849611783922725e-10,-2.7364944862499976e-12,
  6.562485707756628e-12,-1.8571137664271774e-12,3.2655876442517257e-13,
  -3.2803011958553056e-14,-1.6861249687202463e-15,1.6863564121130883e-15,
  -4.535817473380558e-16,7.767824684686082e-17,-7.525567293120925e-18,
  -5.61181142339571e-19,
};

// ===================== 2. LEFT chart =====================
static const double LEFT_S_V2X = 0.22;  // s<this -> V2 series
static const double LEFT_S_V4X = 0.22;  // s<this -> V4 series
// V2 ~ c3 s^3 + c5 s^5 + ... + c13 s^13 (6 terms; machine-precise to s~0.25)
static const double LEFT_V2_SER[6] = {
  -0.00034722222222222224,-5.993716931216931e-05,-9.584780092592592e-06,
  -1.5113141062576826e-06,-2.3757434284401892e-07,-3.7806454640352825e-08,
};
// V4 ~ c3 s^3 + ... + c13 s^13. c3,c5,c7 exact (s^7 CORRECTED vs memo);
// c9,c11,c13 refit numerically -- the memo's c9=4644419/17978967982080 is
// WRONG (=2.58e-7); the true value is ~4.13e-8 (series relerr 3.9e-8 -> 2.8e-16).
static const double LEFT_V4_SER[6] = {
  5.5114638447971785e-06,1.179797729276896e-06,2.254363555361819e-07,
  4.1335064263082484e-08,7.405611870477427e-09,1.306301807263956e-09,
};
static const double LEFT_T_MAX = 0.09;  // xt=2*h^2/T_MAX-1  (=H_ATM_HI^2)
static const double LEFT_S_MAX = 1.7115;  // xs=2*s/S_MAX-1
static const int    LEFT_FIN_DP = 2, LEFT_FIN_DL = 16;  // finisher degrees
// LEFT finisher: row-major (dp+1) rows x (dl+1) stride; v += h^6*clenshaw2(...)
static const double LEFT_FIN_COEFFS[51] = {
  -3.5172877955019804e-07,-5.716397786842268e-07,-3.113218020272888e-07,-1.2266203854672106e-07,
  -4.217207364368739e-08,-1.4546700585455367e-08,-4.8228289613926755e-09,-1.5843157374080016e-09,
  -5.114772006848562e-10,-1.633283538103422e-10,-5.1435852639769366e-11,-1.5916993785329346e-11,
  -4.784180248514885e-12,-1.3617286602686701e-12,-3.5095038659270914e-13,-7.361661055689611e-14,
  -1.0196971423451693e-14,3.5098093185754234e-10,5.753045869666625e-10,3.2255017021991364e-10,
  1.343889902789066e-10,4.952068262399114e-11,1.8078193164443326e-11,6.3146414889544686e-12,
  2.156842371167304e-12,7.06512263522954e-13,2.3020750523592065e-13,7.627017290535434e-14,
  3.524652887143155e-14,1.9326792360699652e-14,1.3569794687788124e-14,6.150025404605938e-15,
  2.4058084119446323e-15,-1.8748952531454234e-16,-1.737603145265809e-13,-2.8224946944003653e-13,
  -1.5624023444601561e-13,-5.795507531909518e-14,-1.6191204974224477e-14,-1.8293311483381307e-15,
  -3.366691364823136e-15,-7.397357201825163e-15,-1.3781421637338825e-14,-1.5893840726809995e-14,
  -1.624768286873682e-14,-1.274570942692742e-14,-8.885307243758622e-15,-4.590022802901165e-15,
  -1.8712712634306945e-15,-2.6177680435847486e-16,9.940926371521975e-17,
};
static const double LEFT_FREE_C = 0.033;  // free zone h<=LEFT_FREE_C*v^(-1/3)

// ===================== 3. RIGHT chart =====================
// No Mills/residual tables: Mills ratio m=gbar/phi is EXACT; V2R/V4R and the
// Newton finisher are closed form. Only tunables below.
static const double RIGHT_FREE_C = 0.0039;  // free zone h<=RIGHT_FREE_C*v^1.5
static const int    RIGHT_NEWTON_MAX = 10;  // safeguarded Newton cap

// ===================== 4. Seams =====================
static const double BR_RHO_STAR    = 0.000950704506575233;  // = B(A_MAX), wing seam (W=3)
static const double BR_CTILDE_STAR = 0.6826894921370859;  // = E(2)=2*Phi(1)-1
static const double BR_H_ATM_HI    = 0.3;
static const double BR_H_BOX       = 6.6526957;
// LEFT<->RIGHT seam for the h<H_ATM_HI band.  The LEFT matched finisher is fit to
// s<=LEFT_S_MAX (~v<=1.94) and EXTRAPOLATES for v->2 at the h=0.3/v=2 double
// corner (measured up to 2.2e-15).  RIGHT's exact-equation Newton is machine
// precise for all v>=1.55 (measured <=4.3e-16 down to h=1e-4).  So for h<H_ATM_HI
// route the seam at v=1.70 (LEFT<=6e-16 for v<=1.7, RIGHT<=4.3e-16 for v>=1.7 --
// a wide both-clean overlap [1.55,1.80]).  Threshold price c2left(h)=C(h,1.70)
// is computed per-context from onem_otm (only the region-1 branch reads it).
static const double LEFT_RIGHT_VSEAM = 1.70;
// FROZEN ctl(h) = C(h,1.70), the LEFT/RIGHT seam price, as a direct degree-8
// Chebyshev in h over [0,0.35] (only the region-1 branch h<0.3 reads it).  This
// REPLACES the former per-quote runtime Black evaluation (1-onem_otm) so the
// routing decision costs a small polynomial rather than an erfc+exp pair; the
// scalar context and the grid router BOTH use this fit, so their chart choice is
// identical (bit-identity) and differs from the exact seam only within ~3e-16 of
// c=C(h,1.70), inside the [1.55,1.80] overlap band where LEFT and RIGHT are both
// machine-precise.  Max rel error vs exact on [0,0.30]: 3.0e-16.
static const double CTL_SEAM_A = 0.0;
static const double CTL_SEAM_B = 0.34999999999999998;
static const double CTL_SEAM_C[9] = {
  5.69411183825004552e-01,-3.54689408609523069e-02,-1.93595678763061293e-04,
  1.17429938914507893e-05,1.24345089762734665e-07,-3.44820561639422661e-09,
  -5.12247409033188540e-11,7.73315075222300009e-13,1.54781687689203498e-14,
};
// FROZEN expm1(h) = h * g(h) with g = expm1(h)/h a degree-10 Chebyshev over
// [0,0.32]; used by the LEFT chart (rho = c/expm1(h)) so the vectorized driver
// needs no scalar libm expm1.  Max rel error of expm1 vs libm on (0,0.30]: 1.0e-16.
static const double EXPM1G_A = 0.0;
static const double EXPM1G_B = 0.32000000000000001;
static const double EXPM1G_C[11] = {
  1.08685175678616086e+00,8.92135597544422287e-02,2.40959391829786420e-03,
  4.85615686872454928e-05,7.80950701808076860e-07,1.04506032240316297e-08,
  1.19761623150572147e-10,1.20015967494188412e-12,1.06862115568444210e-14,
  8.56085446518909449e-17,6.23303387482062399e-19,
};
static const double BR_INV_SQRT6   = 0.408248290463863;
// c2(h)=C(h,2): fit of log(price); c2 = exp(clenshaw(C2_COEFFS,...,h))
static const double C2_A = 1e-06, C2_B = 16.0;
static const double C2_COEFFS[27] = {
  -11.15977926788583,-14.13647690236051,-3.5202053543371257,
  -0.12345627351402545,0.030583580538905038,-0.006674222116672491,
  0.00110912973394948,-5.833776949976273e-05,-5.1428405802530105e-05,
  2.7647020957631936e-05,-8.610678775583443e-06,1.6976939694259402e-06,
  -4.721770328482338e-08,-1.3323406467516446e-07,7.001612485559119e-08,
  -2.195399279495914e-08,4.1433470191903165e-09,8.578485292281304e-11,
  -4.569023120140554e-10,2.2304053709235968e-10,-6.711062057937207e-11,
  1.1454727387958974e-11,1.040581546645032e-12,-1.7204379905657567e-12,
  7.784114460252105e-13,-2.241232058739196e-13,3.6331272023571214e-14,
};
// cwing(h)=C(h,h/sqrt6) at W=3: fit of log(cwing/h); cwing=h*exp(clenshaw(...))
static const double CW_A = 1e-06, CW_B = 16.0;
static const double CW_COEFFS[23] = {
  -4.529022535754299,1.9212843873241585,-0.4849313948576726,
  0.02103792025431453,0.003497678939874673,0.00023092277530810108,
  -4.854081244003275e-06,-8.81412419400575e-06,-1.703407169522652e-06,
  -1.6199718229786228e-07,1.639125075357084e-08,9.462045696023131e-09,
  1.8471293656424585e-09,1.438632204746918e-10,-2.9174036368722994e-11,
  -1.2849491306555834e-11,-2.3141005462530745e-12,-1.3372823950000397e-13,
  5.135397087705062e-14,1.8773849190362445e-14,3.0695103461226477e-15,
  1.1669919752896463e-16,-8.810120231126233e-17,
};

// NEW payload: 170 doubles = 1360 bytes (Binv 57 + left-series 12 + left-finisher 51 + seam-curves 50).
} // namespace volfi_annulus_broadrange
#endif // VOLFI_ANNULUS_BROADRANGE_HPP
