// volfi_annulus_upper1_tables.hpp -- GENERATED by reproduce/gen/gen_upper_v031.py (ENEG piece) and gen_upper_one.py (seed).  ONE-STEP UPPER chart, v0.3.1.
#pragma once
namespace volfi_annulus { namespace upper1 {
static const double IS2 = 0.70710678118654752440;      // 1/sqrt(2)
static const double TWO_K = 0.79788456080286535588;    // 2/sqrt(2 pi)
static const double ENEG_A = -0x1.999999999999ap-2, ENEG_B = 0x0.0p+0;
static const int NENEG = 15;
static const double ENEG_C[15] = { 0x1.4e1f909209e97p+0, -0x1.577c1bcf6e6a4p-2, 0x1.0c57e7416337bp-5, -0x1.5e02a15402255p-9, 0x1.8f37c41efea14p-13, -0x1.9950267a69d49p-17, 0x1.802edd412f2e9p-21, -0x1.4e68ae7a055e4p-25, 0x1.109019509fa20p-29, -0x1.a329249f41650p-34, 0x1.31e058f27010ap-38, -0x1.a9ba46c70439bp-43, 0x1.1bae702d3a067p-47, -0x1.6b3ac374644ecp-52, 0x1.bf8b6932a6cddp-57 };
static const double S_LO = 0x1.6e9bb28bc6a6ap+0, S_HI = 0x1.347e2a2675fe2p+2;
static const int NX0 = 12;
static const double X0C[12] = { 0x1.56326fa90541ap+1, 0x1.c419d578ae050p+0, 0x1.c511bebfe160bp-9, -0x1.2cb4baabddcddp-8, 0x1.d2fd7ffe10a2cp-10, -0x1.1890ccfcacd25p-11, 0x1.24b5ef472640ap-13, -0x1.105f28a288111p-15, 0x1.c07f44bcbe016p-18, -0x1.36d70cd64c412p-20, 0x1.2d8337304f112p-23, -0x1.e2d001fb6752bp-32 };
static const double SGMIN = 0x1.a6f74f18a41dep-2, SGMAX = 0x1.b1ccede2b7965p-1, ZMAX = 0x1.9d9849fec64ecp-1;
static const double R0[6] = { -0x1.42aa26fce3948p-1, 0x1.6cba2a3128f98p-4, -0x1.322126d170e40p-5, 0x1.506be66e8102cp-8, -0x1.2429e1b9a1413p-8, -0x1.ffb009858b212p-9 };   // ascending powers of Z
static const double R1[4] = { 0x1.efbe218591966p-4, -0x1.bc4a94f50a9f0p-6, 0x1.70c8bbc044fecp-8, -0x1.86b58c812cf8fp-10 };   // ascending powers of Z
static const double R2[2] = { 0x1.cd8f0cc92ca87p-8, 0x1.431357458faadp-7 };   // ascending powers of Z
static const double R3[1] = { 0x1.bfb353e72dacdp-10 };   // ascending powers of Z
} } // namespace volfi_annulus::upper1
